spring.application.name=feedback

spring.datasource.url=jdbc:postgresql://localhost:5432/feedbackdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
server.port=8080
	
jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

report.service.url=http://localhost:8081/api/reports
